export enum DataType {
  CodecId,
  AvlDataCount,
  Timestamp,
  Priority,
  Latitude,
  Longitude,
  Altitude,
  Angle,
  Satellites,
  Speed,
  EventIoId,
  IoCount,
  IoCount1B,
  IoId1B,
  IoValue1B,
  IoCount2B,
  IoId2B,
  IoValue2B,
  IoCount4B,
  IoId4B,
  IoValue4B,
  IoCount8B,
  IoId8B,
  IoValue8B,
  // Tcp types
  Preamble,
  AvlDataArrayLength,
  Crc,
  // Codec 8 Extended types
  ExtendedIoCount1B,
  ExtendedIoCount2B,
  ExtendedIoCount4B,
  ExtendedIoCount8B,
  ExtendedIoCountXB,
  ExtendedEventIoId,
  ExtendedIoCount,
  ExtendedIoId1B,
  ExtendedIoId2B,
  ExtendedIoId4B,
  ExtendedIoId8B,
  ExtendedIoIdXB,
  ExtendedIoValueXB,
  ExtendedElementLength,
  // Codec 16 types
  EventIoIdCodec16,
  OriginType,
  IoId1BCodec16,
  IoId2BCodec16,
  IoId4BCodec16,
  IoId8BCodec16,
  // Codec7 types
  PriorityGh,
  TimestampGh,
  GlobalMask,
  GpsElementMask,
  LongitudeGh,
  LatitudeGh,
  AngleGh,
  SpeedGh,
  // GpsIO elements for Codec7
  CellIdAndLocalAreaGh,
  SignalQualityGh,
  OperatorCodeGh,
  // Udp types
  Length,
  PacketId,
  PacketType,
  AvlPacketId,
  ImeiLength,
  Imei
}

